### PR TITLE
Add cookiecutter base and docs

### PR DESCRIPTION
**Pull request by nicain**
Add first pass at documentation. Resolves 2 by using cookiecutter templating.

### CODE REVIEW

**Comment by nicain** [comment]
@corinneteeter Ping me if you need any input on resolving make_pink.py, and pulling in the PR.

**Comment by corinneteeter** [comment]
Closing while we make dev branch.

**Comment by nicain** [comment]
Now targeting dev; @corinneteeter, can you please reopen this PR?

**Comment by corinneteeter** [comment]
Hmm, I don't see any pull requests?

________________________________

**Comment by nicain** [comment]
Yeah GitHub quirk

https://github.com/AllenInstitute/ephys_pink_noise/pulls?q=is%3Apr+is%3Aclosed <https://github.com/AllenInstitute/ephys_pink_noise/pulls?q=is:pr+is:closed>

The issue filter by default hides closed issues.  Go to issue 3 on the link above, and at the bottom there should be a button to reopen

Best,
-n

**Comment by corinneteeter** [comment]
I have several concerns:  

CONTRIBUTING.rst.  I am not sure I want to invite contributions.  This code is promised as is.  

In the README.md: "What is ephys_pink_noise".  Is this necessary?

What happened to the list of requirements to run the code?.

Honestly, all this seems like a lot of overhead for non-software engineers to wade though just to run a script.  Can the README be altered to say how to simply download the necessary file--I'm not sure what the rules are on the formatting of the README file.

**Comment by nicain** [comment]
@corinneteeter 
- [ ] Remove CONTRIBUTING.rst, and set to not be re-made from update.sh
- [ ] README.md is just built from the template, and we can change it to make it as simple or complex as you want.
- [ ] Absolutely.  Most of this is boiler plate to get the website to build.  README.md can have download instructions.

Ill make some changes, and you can tell me what you think.

**Pull request closed without merging**
